import * as yup from "yup";

export const validationSchema = yup.object({
    date: yup.string().required("Date is required"),
    hemoglobin: yup.number().typeError("Hemoglobin must be a number").required("Hemoglobin is required"),
    hematocrit: yup.number().typeError("Hematocrit must be a number").required("hematocrit is required"),
    whiteBloodCell: yup.number().typeError("White blood cell must be a number").required("White blood cell is required"),
    platelets: yup.number().typeError("Platelets must be a number").required("Platelets are required"),
    glucose: yup.number().typeError("Glucose must be a number").required("Glucose is required"),
    cholesterolHDL: yup.number().typeError("Cholesterol HDL must be a number").required("Cholesterol HDL is required"),
    cholesterolLDL: yup.number().typeError("Cholesterol LDL must be a number").required("Cholesterol LDL is required"),
    triglycerides: yup.number().typeError("Triglycerides must be a number").required("Triglycerides are required"),
    redBloodCell: yup.number().typeError("Red blood cell must be a number").required("Red blood cell is required"),
    meanCorpuscularVolume: yup.number().typeError("Mean corpuscular volume must be a number").required("Mean corpuscular volume is required"),
    meanCorpuscularHemoglobin: yup.number().typeError("Mean corpuscular hemoglobin must be a number").required("Mean corpuscular hemoglobin is required"),
    meanCorpuscularHemoglobinConcentration: yup.number().typeError("Mean corpuscular hemoglobin concentration must be a number").required("Mean corpuscular hemoglobin concentration is required"),
    redCellDistributionWidth: yup.number().typeError("Red cell distribution width must be a number").required("Red cell distribution width is required"),
    bloodUreaNitrogen: yup.number().typeError("Blood urea nitrogen must be a number").required("Blood urea nitrogen is required"),
    creatinine: yup.number().typeError("Creatinine must be a number").required("Creatinine is required"),
    sodium: yup.number().typeError("Sodium must be a number").required("Sodium is required"),
    potassium: yup.number().typeError("Potassium must be a number").required("Potassium is required"),
    chloride: yup.number().typeError("Chloride must be a number").required("Chloride is required"),
    bicarbonate: yup.number().typeError("Bicarbonate must be a number").required("Bicarbonate is required"),
    calcium: yup.number().typeError("Calcium must be a number").required("Calcium is required"),
    magnesium: yup.number().typeError("Magnesium must be a number").required("Magnesium is required"),
    neutrophils: yup.number().typeError("Neutrophils must be a number").required("Neutrophils are required"),
    lymphocytes: yup.number().typeError("Lymphocytes must be a number").required("Lymphocytes are required"),
    monocytes: yup.number().typeError("Monocytes must be a number").required("Monocytes are required"),
    eosinophils: yup.number().typeError("Eosinophils must be a number").required("Eosinophils are required"),
    basophils: yup.number().typeError("Basophils must be a number").required("Basophils are required"),
})