// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Data.Migrations
{
    [DbContext(typeof(ManagementContext))]
    [Migration("20240928164833_cardiacCathStudyTypeData")]
    partial class cardiacCathStudyTypeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CardiacCatheterizationStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BlockageEachCoronaryArtery")
                        .HasColumnType("REAL");

                    b.Property<double>("BloodFlowCoronaryArteries")
                        .HasColumnType("REAL");

                    b.Property<string>("CardiacChamberFunctions")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChambersLeftAtrium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChambersLeftVentricle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChambersRightAtrium")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChambersRightVentricle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conclusion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionAbnormalities")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionComplications")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiastolicPressureAorta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiastolicPressurePulmonaryArteries")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LeftVentricularEjectionFraction")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationMainCoronaryArteries")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PressureGradientValves")
                        .HasColumnType("REAL");

                    b.Property<string>("StructuralAbnormalities")
                        .HasColumnType("TEXT");

                    b.Property<int>("SystolicPressureAorta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystolicPressurePulmonaryArteries")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValvularInsufficiencyAortic")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValvularInsufficiencyMitral")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValvularInsufficiencyPulmonary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValvularInsufficiencyTricuspid")
                        .HasColumnType("TEXT");

                    b.Property<double>("VelocityBloodFlow")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("CardiacCatheterizationStudies");
                });

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Core.Entities.AppointmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentStatusName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppointmentStatuses");
                });

            modelBuilder.Entity("Core.Entities.AppointmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppointmentTypes");
                });

            modelBuilder.Entity("Core.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiseaseHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseHistoryId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Core.Entities.BloodTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Basophils")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Bicarbonate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("BloodUreaNitrogen")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Calcium")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Chloride")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("CholesterolHDL")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("CholesterolLDL")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Creatinine")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Eosinophils")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Glucose")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Hematocrit")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Hemoglobin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Lymphocytes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Magnesium")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MeanCorpuscularHemoglobin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MeanCorpuscularHemoglobinConcentration")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MeanCorpuscularVolume")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Monocytes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Neutrophils")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Platelets")
                        .HasColumnType("int");

                    b.Property<decimal?>("Potassium")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RedBloodCell")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RedCellDistributionWidth")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Triglycerides")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("WhiteBloodCell")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("BloodTests");
                });

            modelBuilder.Entity("Core.Entities.CardiologySurgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnesthesiaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardiacCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complications")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("IntraoperativeFindings")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsElective")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMinimallyInvasive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationRoom")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostOpDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostOperativeInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostOperativeStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreOpDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurgeryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurgicalTeam")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("CardiologySurgeries");
                });

            modelBuilder.Entity("Core.Entities.Diagnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conclusions")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpPlan")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendations")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("Core.Entities.DiseaseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChronic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Treatment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DiseaseHistories");
                });

            modelBuilder.Entity("Core.Entities.Echocardiogram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodFlow")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardiacDimensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalImpression")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EjectionFraction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Findings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indications")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementCardiacWalls")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PulmonaryArterialPressure")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValveFunction")
                        .HasColumnType("TEXT");

                    b.Property<string>("VelocitiesBloodFlows")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Echocardiograms");
                });

            modelBuilder.Entity("Core.Entities.Electrocardiogram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abnormalities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artifacts")
                        .HasColumnType("TEXT");

                    b.Property<double>("BloodPressureDiastolic")
                        .HasColumnType("REAL");

                    b.Property<double>("BloodPressureSystolic")
                        .HasColumnType("REAL");

                    b.Property<string>("CharacteristicWaves")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedFindings")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRhythm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interpretation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntervalsSegments")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Electrocardiograms");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.AdditionalTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolterStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Results")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolterStudyId");

                    b.ToTable("AdditionalTestResults");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.ArrhythmiaEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartRateDuringEvent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolterStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolterStudyId");

                    b.ToTable("ArrhythmiaEvents");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.ClinicalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Findings")
                        .HasColumnType("TEXT");

                    b.Property<int>("HolterStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendations")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolterStudyId");

                    b.ToTable("ClinicalEvaluations");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.HolterStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conclusion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyDuration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeHeartRhythm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("HolterStudies");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.MedicationAdministration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AdministrationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<int>("HolterStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolterStudyId");

                    b.ToTable("MedicationAdministrations");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.PatientSymptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HolterStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SymptomDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymptomName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolterStudyId");

                    b.ToTable("PatientSymptoms");
                });

            modelBuilder.Entity("Core.Entities.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardiacProcedures")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyDiseases")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HighBloodPressure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hyperlipidemia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medications")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obesity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreviousHeartDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Smoking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemicDiseases")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("Core.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT");

                    b.Property<int>("SurgeryFollowUpId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurgeryFollowUpId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Core.Entities.NoteStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteStatusName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoteStatuses");
                });

            modelBuilder.Entity("Core.Entities.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("NoteStatusId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedDoctor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarnetIdentification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyDoctor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringDoctor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Core.Entities.PatientStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientStatusName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatientStatuses");
                });

            modelBuilder.Entity("Core.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BloodTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardiacCatheterizationStudyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardiologySurgeryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EchocardiogramId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EcocardiogramId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElectrocardiogramId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StressTestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("BloodTestId");

                    b.HasIndex("CardiacCatheterizationStudyId");

                    b.HasIndex("CardiologySurgeryId");

                    b.HasIndex("EchocardiogramId");

                    b.HasIndex("ElectrocardiogramId");

                    b.HasIndex("StressTestId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Core.Entities.PhysicalExamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbnormalEcgFindings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conclusion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseInducedSymptoms")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeakPressure")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PhysicalExaminations");
                });

            modelBuilder.Entity("Core.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Core.Entities.StressTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbnormalEcgFindings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conclusion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseInducedSymptoms")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseProtocol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indications")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxBloodPressureDiastolic")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxBloodPressureSystolic")
                        .HasColumnType("REAL");

                    b.Property<string>("MaxHeartRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeakPressure")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("StressTests");
                });

            modelBuilder.Entity("Core.Entities.SurgeryFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardiologySurgeryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complications")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionalAssessment")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFollowUpComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendations")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardiologySurgeryId");

                    b.ToTable("SurgeryFollowUps");
                });

            modelBuilder.Entity("Core.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medication")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherTreatments")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideEffects")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentMonitoring")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentOutcome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bb5e8f1b-e6ef-476e-b27d-36dfb2baf9ff",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "637bdd2d-51aa-4141-b69a-9181bb725a6b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CardiacCatheterizationStudy", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("CardiacCatheterizationStudies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", "AppUser")
                        .WithMany("Appointments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.AppointmentStatus", "AppointmentStatus")
                        .WithMany()
                        .HasForeignKey("AppointmentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AppointmentType", "AppointmentType")
                        .WithMany()
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("AppointmentType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Attachment", b =>
                {
                    b.HasOne("Core.Entities.DiseaseHistory", "DiseaseHistory")
                        .WithMany("Attachments")
                        .HasForeignKey("DiseaseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiseaseHistory");
                });

            modelBuilder.Entity("Core.Entities.BloodTest", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("BloodTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.CardiologySurgery", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", "AppUser")
                        .WithMany("CardiologySurgeries")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("CardiologySurgery")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Diagnostic", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Diagnostics")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.DiseaseHistory", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("DiseaseHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Echocardiogram", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Echocardiograms")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Electrocardiogram", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Electrocardiograms")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.AdditionalTestResult", b =>
                {
                    b.HasOne("Core.Entities.HolterStudyInfo.HolterStudy", "HolterStudy")
                        .WithMany("AdditionalTestResults")
                        .HasForeignKey("HolterStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolterStudy");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.ArrhythmiaEvent", b =>
                {
                    b.HasOne("Core.Entities.HolterStudyInfo.HolterStudy", "HolterStudy")
                        .WithMany("ArrhythmiaEvents")
                        .HasForeignKey("HolterStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolterStudy");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.ClinicalEvaluation", b =>
                {
                    b.HasOne("Core.Entities.HolterStudyInfo.HolterStudy", "HolterStudy")
                        .WithMany("ClinicalEvaluations")
                        .HasForeignKey("HolterStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolterStudy");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.HolterStudy", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("HolterStudies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.MedicationAdministration", b =>
                {
                    b.HasOne("Core.Entities.HolterStudyInfo.HolterStudy", "HolterStudy")
                        .WithMany("MedicationAdministrations")
                        .HasForeignKey("HolterStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolterStudy");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.PatientSymptom", b =>
                {
                    b.HasOne("Core.Entities.HolterStudyInfo.HolterStudy", "HolterStudy")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("HolterStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolterStudy");
                });

            modelBuilder.Entity("Core.Entities.MedicalHistory", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Medication", b =>
                {
                    b.HasOne("Core.Entities.SurgeryFollowUp", "SurgeryFollowUp")
                        .WithMany("MedicationsPrescribed")
                        .HasForeignKey("SurgeryFollowUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurgeryFollowUp");
                });

            modelBuilder.Entity("Core.Entities.Notes", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", "AppUser")
                        .WithMany("Notes")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.NoteStatus", "NoteStatus")
                        .WithMany()
                        .HasForeignKey("NoteStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("NoteStatus");
                });

            modelBuilder.Entity("Core.Entities.Patient", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", "AppUser")
                        .WithMany("Patients")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.PatientStatus", "PatientStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("PatientStatus");
                });

            modelBuilder.Entity("Core.Entities.Photo", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", "AppUser")
                        .WithOne("Photo")
                        .HasForeignKey("Core.Entities.Photo", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.BloodTest", "BloodTest")
                        .WithMany("BloodTestPhotos")
                        .HasForeignKey("BloodTestId");

                    b.HasOne("CardiacCatheterizationStudy", "CardiacCatheterizationStudy")
                        .WithMany("CardiacCathStudyImages")
                        .HasForeignKey("CardiacCatheterizationStudyId");

                    b.HasOne("Core.Entities.CardiologySurgery", "CardiologySurgery")
                        .WithMany("SurgeryPhotos")
                        .HasForeignKey("CardiologySurgeryId");

                    b.HasOne("Core.Entities.Echocardiogram", "Echocardiogram")
                        .WithMany("PhotosImageEco")
                        .HasForeignKey("EchocardiogramId");

                    b.HasOne("Core.Entities.Electrocardiogram", "Electrocardiogram")
                        .WithMany("Images")
                        .HasForeignKey("ElectrocardiogramId");

                    b.HasOne("Core.Entities.StressTest", "StressTest")
                        .WithMany("Photos")
                        .HasForeignKey("StressTestId");

                    b.Navigation("AppUser");

                    b.Navigation("BloodTest");

                    b.Navigation("CardiacCatheterizationStudy");

                    b.Navigation("CardiologySurgery");

                    b.Navigation("Echocardiogram");

                    b.Navigation("Electrocardiogram");

                    b.Navigation("StressTest");
                });

            modelBuilder.Entity("Core.Entities.PhysicalExamination", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("PhysicalExaminations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.Prescription", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Prescription")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.StressTest", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("StressTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Core.Entities.SurgeryFollowUp", b =>
                {
                    b.HasOne("Core.Entities.CardiologySurgery", "CardiologySurgery")
                        .WithMany("SurgeryFollowUps")
                        .HasForeignKey("CardiologySurgeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardiologySurgery");
                });

            modelBuilder.Entity("Core.Entities.Treatment", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardiacCatheterizationStudy", b =>
                {
                    b.Navigation("CardiacCathStudyImages");
                });

            modelBuilder.Entity("Core.Entities.BloodTest", b =>
                {
                    b.Navigation("BloodTestPhotos");
                });

            modelBuilder.Entity("Core.Entities.CardiologySurgery", b =>
                {
                    b.Navigation("SurgeryFollowUps");

                    b.Navigation("SurgeryPhotos");
                });

            modelBuilder.Entity("Core.Entities.DiseaseHistory", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Core.Entities.Echocardiogram", b =>
                {
                    b.Navigation("PhotosImageEco");
                });

            modelBuilder.Entity("Core.Entities.Electrocardiogram", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Core.Entities.HolterStudyInfo.HolterStudy", b =>
                {
                    b.Navigation("AdditionalTestResults");

                    b.Navigation("ArrhythmiaEvents");

                    b.Navigation("ClinicalEvaluations");

                    b.Navigation("MedicationAdministrations");

                    b.Navigation("PatientSymptoms");
                });

            modelBuilder.Entity("Core.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CardiologySurgeries");

                    b.Navigation("Notes");

                    b.Navigation("Patients");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BloodTests");

                    b.Navigation("CardiacCatheterizationStudies");

                    b.Navigation("CardiologySurgery");

                    b.Navigation("Diagnostics");

                    b.Navigation("DiseaseHistories");

                    b.Navigation("Echocardiograms");

                    b.Navigation("Electrocardiograms");

                    b.Navigation("HolterStudies");

                    b.Navigation("MedicalHistories");

                    b.Navigation("PhysicalExaminations");

                    b.Navigation("Prescription");

                    b.Navigation("StressTests");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Core.Entities.StressTest", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Core.Entities.SurgeryFollowUp", b =>
                {
                    b.Navigation("MedicationsPrescribed");
                });
#pragma warning restore 612, 618
        }
    }
}
